Fix Storybook Build
minio/mds pull request #456
Opened 2023-08-15 18:24 UTC by dvaldivia

2023-08-15 18:26 UTC, bexsoft requested changes

2023-08-15 18:26 UTC, bexsoft commented on package.json
> -    "rollup-plugin-terser/**/terser": "^5.19.2"
Please don't remove this resolution

2023-08-15 18:37 UTC, dvaldivia commented on package.json
> -    "rollup-plugin-terser/**/terser": "^5.19.2"
ready

2023-08-15 18:43 UTC, bexsoft approved these changes

2023-08-16 14:44 UTC, prakashsvmx approved these changes

2023-08-17 19:00 UTC, bexsoft approved these changes

2023-08-17 19:01 UTC, merged