Helptip improvements and placement in mds components
minio/mds pull request #505
Opened 2023-09-20 23:13 UTC by jinapurapu

Improves HelpTip styling and behavior and includes HelpTip in other mds components to allow correct placement.

2023-09-21 00:28 UTC, bexsoft requested changes

2023-09-21 00:28 UTC, bexsoft commented on src/components/InputLabel/InputLabel.tsx
> +        </HelpTip>
We need to add a validation here to not throw the component in case no help tip is set

```suggestion
        {helpTip ? <HelpTip placement={helpTipPlacement} content={helpTip}>
          {children}
        </HelpTip> : children}
```

2023-09-21 00:28 UTC, bexsoft commented on src/components/Checkbox/Checkbox.types.ts
> +  helpTipPlacement?: "top" | "bottom" | "left" | "right";
Let's add this as an enum in `global.types.ts` and use the enum parameters in all `helpTipPlacement` properties to have just one value

2023-09-21 00:28 UTC, bexsoft commented on src/components/HelpTip/HelpTip.tsx
> +  ({ theme, placement = "hide" }) => {
Placement type `hide` doesn't exist in the options

2023-09-21 00:28 UTC, bexsoft commented on src/components/HelpTip/HelpTip.tsx
> +let placementOptions = new Set<string>(["top", "bottom", "left", "right"]);
This can be changed in favor of the enum  from `global.types.ts`

2023-09-21 00:28 UTC, bexsoft commented on src/components/Checkbox/Checkbox.types.ts
> +  helpTip?: any;
Let's avoid the use of `any` as much as possible, I think this can be set as `React.ReactNode`

2023-09-21 00:28 UTC, bexsoft commented on src/components/HelpTip/HelpTip.tsx
> +        }, 50000)
Is 50 seconds the correct value here?

2023-09-21 15:30 UTC, jinapurapu commented on src/components/HelpTip/HelpTip.tsx
> +        }, 50000)
This is to close the HelpTip without external click, I didn't want it to close too quickly if people were still reading them.

2023-09-23 00:29 UTC, bexsoft approved these changes

2023-09-23 00:29 UTC, merged