Added New Theming icons
minio/mds pull request #628
Opened 2024-01-11 21:21 UTC by bexsoft

## What does this do?

Added new Theming icons for dark / Light Mode

## How does it look?

<img width="115" alt="Screenshot 2024-01-11 at 3 21 11 p m" src="https://github.com/minio/mds/assets/33497058/96b67694-687d-4573-aae5-3f061efc6a74">
<img width="115" alt="Screenshot 2024-01-11 at 3 21 05 p m" src="https://github.com/minio/mds/assets/33497058/c86b0f24-6558-47fe-ac89-1af9c1843d50">
<img width="142" alt="Screenshot 2024-01-11 at 3 21 02 p m" src="https://github.com/minio/mds/assets/33497058/05b5ca26-2213-4009-bb59-83ed0db68e57">

2024-01-11 21:27 UTC, dvaldivia requested changes

2024-01-11 21:27 UTC, dvaldivia commented on src/components/Icons/AutoModeIcon.tsx
> +// Copyright (c) 2023 MinIO, Inc.
2024

2024-01-11 21:28 UTC, dvaldivia commented on src/components/Icons/AutoModeIcon.tsx
> +// Copyright (c) 2023 MinIO, Inc.
```suggestion
// Copyright (c) 2024 MinIO, Inc.
```

2024-01-11 21:28 UTC, dvaldivia commented on src/components/Icons/LightModeIcon.tsx
> +// Copyright (c) 2023 MinIO, Inc.
```suggestion
// Copyright (c) 2024 MinIO, Inc.
```

2024-01-11 23:35 UTC, kaankabalak approved these changes

2024-01-12 00:06 UTC, dvaldivia approved these changes

2024-01-12 00:06 UTC, merged