Default InputBox to Size large and fix Border on button
minio/mds pull request #766
Opened 2024-04-26 17:42 UTC by dvaldivia

<img width="910" alt="Screenshot 2024-04-26 at 10 41 27 AM" src="https://github.com/minio/mds/assets/18384552/c846562c-64e4-4332-bb1c-597e9cb03540">

2024-04-26 17:51 UTC, bexsoft requested changes

2024-04-26 17:51 UTC, bexsoft commented on src/components/InputBox/InputBox.tsx
> +        height: sizeMode === "small" ? 25 : 33,
Wrong sizes

<img width="683" alt="Screenshot 2024-04-26 at 11 50 58 a m" src="https://github.com/minio/mds/assets/33497058/6754b7d5-2d9f-4df8-8368-743537dee571">
<img width="1243" alt="Screenshot 2024-04-26 at 11 50 45 a m" src="https://github.com/minio/mds/assets/33497058/5f9fd86b-d803-4e8b-8e6b-2ee77ec6c7d0">

2024-04-26 19:09 UTC, dvaldivia commented on src/components/InputBox/InputBox.tsx
> +        height: sizeMode === "small" ? 25 : 33,
I had to, to fix the problem of overflowing borders and the hover of the button exploding, you can see the problem in the current version of mds.min.dev

<img width="461" alt="Screenshot 2024-04-26 at 12 09 05 PM" src="https://github.com/minio/mds/assets/18384552/415c14d5-efce-4a6b-b767-b74c51f9c00d">

2024-04-27 04:31 UTC, bexsoft approved these changes

2024-04-27 04:31 UTC, merged