Simplify and harden `IColumn<T>` type
minio/mds pull request #976
Opened 2024-09-17 09:38 UTC by ramondeklein

Implement the suggestion in https://github.com/minio/mds/pull/931/files#r1728475980.

This change allows to either render a single element (and allow sorting) or rendering based on the full object.

2024-09-17 11:57 UTC, bayasdev reviewed
Does this also narrow down the types when using `renderFunction` with an `elementKey`?

2024-09-17 12:02 UTC, bayasdev commented on src/components/DataTable/DataTable.types.ts
> -}[keyof T];
I remember doing an intermediary type because the types were not narrowed down and instead returned  an union with all the possible types for the keys of the object.

2024-09-17 12:04 UTC, bayasdev approved these changes

2024-09-17 23:14 UTC, bexsoft requested changes

2024-09-17 23:14 UTC, bexsoft commented on src/components/DataTable/DataTable.types.ts
> +  renderFullObjectFunction: (input: T) => React.ReactNode | string;
We must remove this and just use one render function, the original ideas was to render the values in other way than text (eg. the online indicator), I think we may change this function to receive two parameters, the first one as the element value, and the second one the whole object for that row.  

Also, we need to continue enabling the sort in these columns as it may be required

2024-09-18 08:29 UTC, ramondeklein commented on src/components/DataTable/DataTable.types.ts
> +  renderFullObjectFunction: (input: T) => React.ReactNode | string;
My intent was not to change functionality with this PR, but to simplify/improve the typing. Although I agree with your points (see the [original comment](https://github.com/minio/mds/pull/931/files#r1728475980)):

> I would prefer to change `enableSort?: boolean` to `sortFunction` that returns the string to sort on. That also allows sorting properly based on time, special columns, ...

Changing that is not the goal of this PR and maybe should be done in a different PR. I don't have the time to work on that...

2024-09-18 08:40 UTC, ramondeklein commented on src/components/DataTable/DataTable.types.ts
> +  renderFullObjectFunction: (input: T) => React.ReactNode | string;
Although I agree on your "sorting" argument, I do like that `renderFunction` is isolated to the `elementKey` type. It allows to implement and reuse render functions based on just a simple type (i.e. rendering date/time) without the need to know anything of the parent object. That allows re-use of rendering functions.

it may be possible to achieve the same when specifying:
```typescript
renderFunction: (
    (input: T[keyof T]) => React.ReactNode | string) | 
    (input: T[keyof T], parent T) => React.ReactNode | string)
)
```
Without specifying the `elementKey` this would become:
```typescript
renderFunction: (parent T) => React.ReactNode | string)
```
The internals of the data-table can detect whether `elementKey` is specified and call it with the appropriate arguments.

2024-09-20 09:41 UTC, ramondeklein commented
We need to fix the build issue in `ColumnsSelector.tsx`.

2024-09-20 14:05 UTC, bayasdev commented
@ramondeklein I'm working on a full refactor of the `DataTable` component, I already sorted out the type problems and removed all the `any` instances.

Before my previous change there was a `renderFullObject` boolean, however I was unable to do conditional types for the `renderFunction` callback value. You can do an union but on the consuming application you would have to narrow down the types.

2024-09-20 19:01 UTC, closed without merging